### ISSUE TITLE
验证码图片显示不出来

### ISSUE THREAD

**Issue by running8gubin** [deatil/dcat-login-captcha#3]

**Comment by deatil** [comment]
日志里面有报错信息吗？

**Comment by running8gubin** [comment]
没有报错日志，前几天还正常的。今天才发现这个情况

**Comment by deatil** [comment]
> 没有报错日志，前几天还正常的。今天才发现这个情况

有更新过什么吗？该说没有动过的话不会出现不显示。可以的话，打开debug记录下日志看看

**Comment by deatil** [comment]
> 没有报错日志，前几天还正常的。今天才发现这个情况

好了。更新下新版，这个是dcat升级到20后出现的问题，dcat20好像改了些东西，以前的写法暂时不能用了

**Comment by running8gubin** [comment]
解决了

**Comment by deatil** [comment]
> 解决了

ok
