### ISSUE TITLE
现在做的是登录表单的验证码，其他表单呢 要不要搞个兼容？

### ISSUE THREAD

**Issue by githubfisher** [deatil/dcat-login-captcha#6]
$(captchaHtml).insertAfter($("#login-form fieldset.form-label-group").get(1));
#login-form  和 get(1)的1
是否可以改成可配置的？

**Comment by deatil** [comment]
兼容估计不太行。配置那个估计得行，后面看下怎么配置好些

**Comment by deatil** [comment]
可配置的加上了。兼容的不行
